apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: t8i9ykkyc-python 
  janus-idp.io/tekton: t8i9ykkyc-python
  backstage.io/kubernetes-id: t8i9ykkyc-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: t8i9ykkyc-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml